### ISSUE TITLE
Heroku/Git

### ISSUE THREAD

**Issue by drapergeek** [railsbridge-boston/railsbridge-boston#11]
It seems that trying to teach git along with everything else we're covering a bit overwhelming.  As an opinion, I think our time could be better spent if we skipped the git section and focused more on Ruby/Rails.  If we remove the git requirement we also remove heroku from the learning requirements which would free up even more time. 

If we think it's really important to keep heroku then I think we should add it as an extra credit section towards the end where students commit their entire repo and push up instead of having to fight deploys at each point.

Thoughts?

**Comment by durrantm** [comment]
My opinion is that we should keep both, but make them easier where we can.

git should just be doing git init (once) and then git add's, commit -m's
and git push.  Plus adding the heroku remote.
I think we should be able to explain fairly easily.  Perhaps we could spend
an extra 5 mins on git at the beginning to increase comfort with it.
git is used for all rails jobs I've done (excluding the one svn...), but
also, as you've noted for heroku too, so it's an immediate win.
I also think we should keep heroku.  The rush of a real rails web site with
a link people can send is pretty big.

On a related note I plan to change my presentation from the 'overview of
editors, etc' style to a more hands-on command line session.   Given the
struggles we've seen there it would be good to run everyone through - and
have them actually follow along - some basic commands such as cd, pwd, cat,
rm, ls, cp, cd ~, mkdir, etc.
This might also help address some of the command line struggles that make
using git hard.  It's easy to forget how even up-arrowing for recalling
previous commands is something you have to learn...

Michael.

On Mon, Nov 26, 2012 at 9:13 PM, Jason Draper notifications@github.comwrote:

> It seems that trying to teach git along with everything else we're
> covering a bit overwhelming. As an opinion, I think our time could be
> better spent if we skipped the git section and focused more on Ruby/Rails.
> If we remove the git requirement we also remove heroku from the learning
> requirements which would free up even more time.
> 
> If we think it's really important to keep heroku then I think we should
> add it as an extra credit section towards the end where students commit
> their entire repo and push up instead of having to fight deploys at each
> point.
> 
> Thoughts?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/railsbridge-boston/railsbridge-boston/issues/11.

## 

Cheers, Michael.

**Comment by mauricio** [comment]
@durrantm +1 on the hands on command line presentation, many of the students didn't know what they where doing with the command line and we usually had to explain what all commands did again.

**Comment by brendankemp** [comment]
+1 on simplifying the git component. Maybe we could ease the deploy cycle by giving some more instruction on Friday night? It sounds like it could use some clarification.

**Comment by patricksrobertson** [comment]
:+1: on removing git and heroku.

I spent significant time debugging git / heroku issues with little upside.  In an intermediate course / work situation I'd teach a graduate from the ground up on git.  I'd rather the graduate know nothing about dVCS, know more about Ruby/Rails and then add in dVCS knowledge at the appropriate time when the student can appreciate a proper git based workflow.

Problems I ran into:
- `git commit` without the -m .  It isn't intuitive at all to a student that they should be exiting vi with :q 
- `git commit` without a preceding `git add .` and sometimes coupled with a push to heroku.  The heroku app would be a in a weird state.
- Not teaching `git status`.  Students had no way to debug the above statement without me teaching them a magic invokation.

**Comment by drapergeek** [comment]
I ran into the same types of issues that @patricksrobertson did.  I understand that most rails jobs are going to require their users to know git but this course is intended to be an intro to Ruby/Rails, not git and I think it bogs down things a lot.

I'd rather remove it completely other than a final page with simple steps to just get the app on heroku.

**Comment by brendankemp** [comment]
> I think it bogs down things a lot.

So this is detracting from the essential tasks of building an app and learning about Ruby? OK I'm in favor, let's try taking it out. We're probably better off acknowledging that we can't give a proper introduction to all of a developer's tools, not in the time we have. Like @patricksrobertson said, the students will have a much better appreciation for what git is for once they have coded a little more.

**Comment by danchoi** [comment]
:punch: I am just inspired by @patricksrobertson to write my first GitHub Emoji

**Comment by danchoi** [comment]
It may be worth raising this proposal on the RailsBridge SF google group because those people have been through this curriculum with more students than anybody. I favor simplification too.

I'm wildly guessing that Git was added to the curriculum because you need it to push to Heroku. But if there was a way to push student apps to live web without forcing them learn Git along with everything else, I think that would be great.

Maybe this is calling for another teaching platform innovation by RailsBridge Boston. This could just be a magic Bash script that just handles all the Git stuff and pushes up to Heroku. Thoughts?

**Comment by bcarreno** [comment]
:+1: on removing git and heroku

It's a lot to cover and these would be easy to remove in order to simplify the curriculum.  We can always move these steps to a separate section they can cover on their own.

**Comment by alexch** [comment]
Railsbridge SF lurker chiming in..!

When we designed the curriculum we thought both Git and Heroku were important since the purpose of the workshop is to demystify the whole process of building _and launching_ a web site. It's arguably more valuable to teach Heroku than, say, ActiveRecord since more novices understand what a database is than what it means (and how simple it is) to deploy code through a VCS to a cloud app host. We're not teaching programming; we're introducing web development, to encourage future exploration.

That said, we have had a lot of requests for a more modular curriculum, and a recent pull request did split out Heroku behind "optionally deploy" links, at least during the installfest. 

So yes, splitting out Git and Heroku does sound like a righteous move, as long as they're not buried. 

(And writing a custom railsbridge deploy script seems pretty far off the mark to me.)

**Comment by danchoi** [comment]
Thanks for the backstory! :thumbsup:

**Comment by danchoi** [comment]
I'm not sure I agree that Git and Heroku are that important for an introductory 1-day course. I've managed to write plenty of Rails apps without using either. Deploying a Rails app using scp or rsync to copy to a server  is not the worst thing in the world if you're a beginner. Of course we want everyone to learn Git eventually and maybe Heroku (though I still never use it outside RailsBridge). But given how brain-fried some students were, it may be worth removing them from the intro curriculum to make it easier to absorb everything else. 

The reason I proposed an simplifying wrapper script for deploying to Heroku is so we can remove the Git part of the curriculum without having to sacrificing the excitement the students feel seeing their first Rails app live on the web where their moms can witness it.

**Comment by dpickett** [comment]
@danchoi I think you might be on to something from an abstraction standpoint, and I totally agree there's a high "cool factor" that I saw with a lot of students when they realized they published something to the web. It's a big deal. I wonder if there's some git GUI's we could incorporate into the material?

**Comment by kookster** [comment]
I agree with what @alexch wrote as the original reasons for including git/heroku.

I think it is important to get to git and heroku, as we are not just teaching ruby here, we are teaching how to make an app, and get it live.  That seems important to me.

I agree there are other ways, but we are trying to help folks get comfortable and feel successful, and there is something victorious about getting a site live.

Now, I would say that this could be left to the very end.

Instead of immediately adding the project to git and deploying after the rails create, I would suggest putting this off to the end of the day, so after you have the site working locally, you add to git, push, and can see it live on heroku.

I also would get rid of the git extra credit, that was confusing, and caused problems.

Perhaps there could be some dVCS intro on the Fri night (along with more of a focus on basic skills like command line shells, text editing and unix concepts and commands)?

I don't like the idea of the wrapper, as it isn't the real thing, or useful after this class.

I like the idea of maybe using a git gui tool in theory, but I am torn, as I see benefit to our students getting comfortable at the command line.

**Comment by danchoi** [comment]
I would be fine with what @kookster and @drapergeek are proposing too -- putting off git and deploy until the end.

I would add (mootly) that the wrapper script I am thinking of could continue to be useful for beginners who want to deploy any rails app to their Heroku accounts after the workshop without dealing with individual git commands. The script would basically do a "save every change I made to this project, prompt me for a commit message, & then deploy everything to Heroku" with one command. This could be generically useful.

**Comment by kookster** [comment]
@danchoi If there could be a generically useful script/task, I withdraw all objections.

If the source for this script was extremely literate/well documented, it could itself serve both as an instrument for teaching how to do this common task when students read the src, without having to worry about the students cutting and pasting commands incorrectly while still learning what they mean.

I am coming around on this one ;)

**Comment by danchoi** [comment]
@kookster You've improved on my suggestion x2 at least :thumbsup:

**Comment by durrantm** [comment]
approach sounds great to me :)

On Wed, Nov 28, 2012 at 12:28 AM, Andrew Kuklewicz <notifications@github.com

> wrote:
> 
> @danchoi https://github.com/danchoi If there could be a generically
> useful script/task, I withdraw all objections.
> 
> If the source for this script was extremely literate/well documented, it
> could itself serve both as an instrument for teaching how to do this common
> task when students read the src, without having to worry about the students
> cutting and pasting commands incorrectly while still learning what they
> mean.
> 
> I am coming around on this one ;)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/railsbridge-boston/railsbridge-boston/issues/11#issuecomment-10791242.

## 

Cheers, Michael.

**Comment by semanticart** [comment]
I realize this thread is old but I thought I'd offer a recent anecdote.

Several of the students in my group this weekend would have benefitted from a script. Several times they forgot to specify a commit message, didn't realize what had happened, and ended up tying their next step, `git push heroku master`, into vim. This was very confusing for them and they ended up (on their own initiative) simply following a script (that is, a series of instructions to follow in order) to avoid getting into a weird state again. If they're already following a manual script, I don't know how much it would hurt to actually make an executable script out of it.

Obviously git is hugely important to day-to-day development.  But for the purposes of the workshop, git is really a means to an end and a checkpoint script would suffice.

The idea of using the contents of that script as documentation / teaching is great. I'd hate to see heroku thrown out with the git bathwater (for reasons mentioned by others) but I'll give a +1 to sanding down some of the rough edges in the process.

**Comment by slothbear** [comment]
What @semanticart  says. I also had multiple students this weekend that did not remember all the commands and syntax. They spent too much time trying to find them in the slides, and didn't remember the commands the next time.

When I found this thread I was ready to say "let's get rid of git!", but I totally see the relevance after reading the whole thread. Still, way too much time was spent diagnosing git errors and waiting for git push/heroku open.

I'm all for a commit script, perhaps after a first-time manual process?  If we decided to go for the one-commit and push at the end of day, are there any dangers that errors/misconfiguration may have slipped in throughout the day? Would they be harder for a TA to diagnose than the one-by-one errors during the day?

**Comment by danchoi** [comment]
OK we just need someone to prototype a bash or Ruby script to hide the details of the git commit and push.

**Comment by slothbear** [comment]
Hm, the implementation details... `git add` and `git push` are easy. What do we use for for a commit message? Maybe the script can take a message as an argument... and default to ... what if the message isn't given?

```
bridge-commit Scaffold a user model
```

**Comment by danchoi** [comment]
How about an interactive script, with a prompt for the message, and a confirm for pushing to Heroku?

**Comment by slothbear** [comment]
That's better! No need to remember anything beyond the script name. Ok, I'll prototype. I won't have a chance to test on all platforms until the end of the week.

**Comment by danchoi** [comment]
Thank you Paul!

**Comment by slothbear** [comment]
I've reconstructed this prototype a bunch of times, but I never ended up with anything nearing the "extremely literate/well documented" mark. Even with just four commands, system-command stuff obscures a lot of the intent. I tried creating methods, but that added a different kind of obfuscation.

So here is a prototype. I could see adding some verbose comments to each of the four command sections. I'm not certain that even a perfect script would be a good learning tool. Command scripting is a much different skill from that of issuing three git commands.

Note I've also used a very _guard clause_-heavy style, exiting as soon as anything goes wrong. Git does the heavy lifting of providing any error messages. I skipped the confirmation for pushing to Heroku for now. I couldn't remember any time we skipped the push during the course.

``` ruby
#!/usr/bin/env ruby
require 'readline'

# Perform git add, commit, and push to Heroku.

status = %x[git status --porcelain]
exit unless $?.success?

if status.empty?
  puts '** No files have been changed, created, or removed.'
  exit
end

exit unless system('git add --all')

message = Readline.readline('enter commit message> ')
exit unless system('git', 'commit', '--message', message)

system 'git push heroku'
```

**Comment by danchoi** [comment]
On a quick glance, looks great to me. Thank you!

**Comment by danchoi** [comment]
I would use

```
system("git commit", "--message", message)
```

to escape any single quotes

**Comment by bcarreno** [comment]
@slothbear do you want to pack it and publish as a gem?  I think you should be the author.

**Comment by slothbear** [comment]
Ok -- I'll publish as a gem. I still have some platform testing to do.  I'll also include Daniel's suggestion.

**Comment by bcarreno** [comment]
Thank you Paul for all your help

**Comment by slothbear** [comment]
The add/commit/push script is now available as a gem: [adcopu](https://github.com/slothbear/adcopu).

I've tested on Mac OS X and Ubuntu 12.04 LTS.  I'll test on Windows tomorrow (unless someone else volunteers).

I'm taking suggestions for:
- a better gem name
- the wording of the commit message prompt, currently `enter commit message (blank to exit)>`
- anything else you'd like to criticize, comment, or improve on.

I never found a way to make the script "extremely literate/well documented" without obscuring the basic operation of four commands. As a compromise for now, I added a **detailed operation** section to the readme.

**Comment by slothbear** [comment]
I tested with Windows 7, so stop volunteering. Windows 7 and Ubuntu 12.04 tests were done after following the Installfest instructions. Mac OS X testing was done on my own non-Installfest development system.

I have an idea for an enhancement already:warning:  Add brightly colored headers to the output before each of the steps -- with the text of the git command being executed. While waiting for the push to complete, students would see the git commands over and over again, perhaps becoming familiar over time?

**Comment by dpickett** [comment]
wow this is cool! @slothbear I think it's important to output the commands that the script is executing to further  learning. Is this something you would welcome as a pull request?

**Comment by slothbear** [comment]
All pull requests, critiques, comments are welcome. Thanks!

**Comment by danchoi** [comment]
Thank you @slothbear !

**Comment by danchoi** [comment]
If @brendankemp is okay with this, we should change the curriculum to incorporate @slothbear 's new tool.

**Comment by danchoi** [comment]
@bcarreno this may have implications for the Git lecture as well

**Comment by slothbear** [comment]
I'd like for a couple of other people to test the tool before it is included in the curriculum. The only requirement is that you be working on the master branch, since `git push heroku master` is hard-coded.

**Comment by bcarreno** [comment]
Still want to change the name?  I thought of `gach` (Git Add Commit pusH) Other options: `gitupdate`, `gitstep`, `gstep`

**Comment by alexch** [comment]
I think the name should be something pronounceable and spellable, like
"push" or "shove" or "deploy" or "check" or "checkin".

Hmm... if it's "check" then you could have variant operations as
parameters, like "check in" and "check out" and "check deploy".

**Comment by danchoi** [comment]
I'll suggest `gph` (git push heroku)  since it's also a short command name that isn't claimed either in rubygems or in the standard unix toolkit.

**Comment by slothbear** [comment]
I'd love to change the name. I tend to like obscure (already have that with adcopu) or short like `gach` (isn't that a Klingon delicacy?). I kind of like the idea of including 'git' in the name, since it only performs git commands. `gitstep` sounds nice and is descriptive.

More ideas! vote!

**Comment by bcarreno** [comment]
@slothbear that's right! _gach_ is a Klingon delicacy consisting of worms, served live.

**Comment by durrantm** [comment]
One more idea:

How about gittyup? (Play on the words/phrases/acronyms: git, up, giddyup,
tty). Easy to pronounce and suggestive of what it's doing. Too silly
perhaps?

Michael.

On Tue, Feb 19, 2013 at 11:26 AM, Paul Morganthall <notifications@github.com

> wrote:
> 
> I'd love to change the name. I tend to like obscure (already have that
> with adcopu) or short like gach (isn't that a Klingon delicacy?). I kind
> of like the idea of including 'git' in the name, since it only performs git
> commands. gitstep sounds nice and is descriptive.
> 
> More ideas! vote!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/railsbridge-boston/railsbridge-boston/issues/11#issuecomment-13781682.

## 

Cheers, Michael.

**Comment by intuedge** [comment]
gitup (simple), githerup (mention heroku, at the risk of crude sexism), or gph (obscure yet practical)

**Comment by dpickett** [comment]
A somewhat obscure fact:

if you name the script git-[name] it will work as a git subcommand. So you could name it git-heroku and this command would be valid:

```
  git heroku
```

**Comment by slothbear** [comment]
I guess the tool's name is up to me, unless someone more official dictates. My favorite of the suggestions is the fun-to-say and memorable `gittyup` :horse_racing: (thanks Michael). My second choice is the descriptive `gitstep` :shoe: (thanks Braulio). I'll rename tomorrow.

**Comment by slothbear** [comment]
The add/commit/push script is now available as a newly named gem: [gittyup](https://rubygems.org/gems/gittyup). With enhancements from the community. Thanks!

**Comment by brendankemp** [comment]
Wooohooo!

**Comment by slothbear** [comment]
Someone asked me...

> If the goal is to get the app live on the web, is git the only way to do it?

Are there easy hosting solutions that would allow us to deploy without git? I wonder if some service besides Heroku would allow Railsbridge students to deploy their apps – and perhaps those services don't require git? Given that Suggestotron doesn't take up a lot of resources, a paid service might even donate free accounts as a sponsorship.

And... it turns out you can deploy to Heroku without git. The `heroku-push` plugin packages everything up and deploys. The process requires a number of steps, which makes me wonder if it is better or worse than a one-time git add/commit/push at the end of the day. Also, the plug-in deploys via an external server, adding even more dependencies to the process. Still... more options, and Heroku appears to be interested in supporting such options.

http://stackoverflow.com/questions/16538166/upload-to-heroku-without-git  
https://github.com/heroku/heroku/issues/514
