### ISSUE TITLE
File not found: /mvc

### ISSUE THREAD

**Issue by kdurr** [railsbridge-boston/railsbridge-boston#111]
The Lecture Slides: Exploring Model View Controller path (http://www.railsbridgeboston.org/mvc) isn't working

**Comment by danchoi** [comment]
Removed from the website

On Sat, Oct 05, 2013 at 09:21 AM, kdurr notifications@github.com wrote:

> from: kdurr notifications@github.com
> date: Sat, Oct 05 06:21 AM -07:00 2013
> to: railsbridge-boston/railsbridge-boston railsbridge-boston@noreply.github.com
> reply-to: railsbridge-boston/railsbridge-boston reply@reply.github.com
> subject: [railsbridge-boston] File not found: /mvc (#111)
> 
> The Lecture Slides: Exploring Model View Controller path (http://www.railsbridgeboston.org/mvc) isn't working
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/railsbridge-boston/railsbridge-boston/issues/111

---

Sent from Vmail
http://danielchoi.com/software/vmail.html
