### ISSUE TITLE
The Intro to Ruby should be an interactive tutorial

### ISSUE THREAD

**Issue by PDegenPortnoy** [railsbridge-boston/railsbridge-boston#112]
Everyone in the room is sitting at a computer with Ruby installed and their fingers are itching to do something.

The Intro to Ruby should be restructured to be an interactive tutorial to introduce everyone to:
- Variables
- Basic Objects: String, Array, Hash
- Basic object methods: String Operations, Array Operations, Hash Operations
- Scope & Blocks
- Control Structures: If, if else, unless, case
- Functions: definition, parameters, return values
- Classes: definition, inheritance, invocation

**Comment by spacewaffle** [comment]
Yeah, I think a code-along in irb would be more useful.

**Comment by eudaimonious** [comment]
Agreed but that would also mean the presentation would have to be slowed down considerably. If you really want to follow along but fall behind and/or get stuck (everyone typos!) you may be very discouraged.

**Comment by PDegenPortnoy** [comment]
Good point; One strategy to counter the risk of needing to pull everyone along is to keep the steps small, focused and incremental.  This could help resolve common issues such as unterminated strings.  Perhaps having the TA spread around would help things to continue moving along.

**Comment by kookster** [comment]
good point about leaving people behind.  maybe have people optionally follow along in irb, and then have time after the lecture to help those who need more time?

Or break it up, and use a break in the middle to catch people up after some smaller length of time/frustration, then bring people back together for the rest of the lecture? Like maybe stop after control structures, then come back and do functions and OOP after?

Hmm, maybe it should just be 2 lectures, and take time out of the 'starting your rails app' section by moving git and heroku to the end after or when we cover routes?

**Comment by PDegenPortnoy** [comment]
I like the idea of extending the instructor lead interactive part.  With TA's spread around, we could help people understand Ruby, get their rails app generated and pushed to heroku and bring everyone along.  Then everyone would have an environment for learning about working in Rails to build functionality.

**Comment by galiat** [comment]
I like the idea of splitting it up so that students can start interacting with with ruby sooner. In the same vein, a lot of good questions were asked during q&a 'What happens if you type...' and having this be interactive would encourage students to try it out for themselves.

**Comment by kookster** [comment]
I feel like this, and the cmdline stuff, both work better something like a demo rather than a lecture, what do you think?

**Comment by durrantm** [comment]
I like the idea of students pairing up with other students and ta's and following along and actually doing at the same time, with plenty of time to address typo's and the like and to ensure that students don't get left behind.  Slow and easy to build confidence.

**Comment by janetriley** [comment]
The Ruby-only curriculum is a hands-on tutorial, and we have minimal lectures planned.  We'll encourage people to work together if they choose.  We're going to end with writing a program in small groups.  

Closing here. Please open new issues at the Ruby curriculum at https://github.com/railsbridge-boston/railsbridge-docs .
