### ISSUE TITLE
People are starting IRB within IRB

### ISSUE THREAD

**Issue by eudaimonious** [railsbridge-boston/railsbridge-boston#114]
Just spoke to three people in a row, at different tables, who had typed 'irb' multiple times. This led to issues accessing a variable they had set in the outer irb and confusion when typing 'exit' did not take them to the command line. In fact, typing exit causes irb to yield a totally unhelpful/confusing stack trace. 

To solve, I suggest: 1. More education on difference between irb and command line (visually and functionally). 2. Amend instructions so that if you are already in IRB (from the last tutorial page) you are not prompted to type irb again.

**Comment by galiat** [comment]
Yes. The syntax used to indicate what is happening on when typing in the console was unclear to some participants. For example:

$ irb

> > 1 + 2
> > => 3

**Comment by janetriley** [comment]
Addressed in VM configuration.
