### ISSUE TITLE
'Link_to' destroy not generating unobtrusive JavaScript, rendering show instead of delete

### ISSUE THREAD

**Issue by alxjrvs** [railsbridge-boston/railsbridge-boston#117]

**Comment by alxjrvs** [comment]
This is in the 'crud with scaffolding' portion

**Comment by thegreatape** [comment]
I believe this is due to generating the app with the `--no-sprockets` flag, which intended to address the "text file not found" issue on Windows. If we can resolve #119, we can drop the `--no-sprockets` flag and this shouldn't be an issue.

**Comment by janetriley** [comment]
#119 resolved: the May 2014 VM doesn't have the --no-sporckets issues, and it has been removed from the directions.
