### ISSUE TITLE
Error Generating User Scaffolding

### ISSUE THREAD

**Issue by eudaimonious** [railsbridge-boston/railsbridge-boston#118]
Anyone else seeing a migration file with "t.e" instead of "t.string"? Why is this happening?

**Comment by janetriley** [comment]
Do you remember the circumstances this bug happened in?

**Comment by slothbear** [comment]
Unless there's a reproducible test case, I'd be willing to guess that the Generate command was not typed correctly. Rails doesn't check the types you pass on the command line. For instance, this command:

```
rails generate model dog name:e
```

attempts to create the table using 'e':

```
    create_table :dogs do |t|
      t.e :name

      t.timestamps
    end
```

**Comment by eudaimonious** [comment]
Agree it was probably a typo.
