### ISSUE TITLE
default text editor?

### ISSUE THREAD

**Issue by kookster** [railsbridge-boston/railsbridge-boston#122]
Many people ended up in the default text editor, nano I think, when forgetting to use -m on commit.  Could we in some way prepare them for this, and should we think about what default text editor it should be (vim?)?

**Comment by duggiefresh** [comment]
I like the idea of setting up Vim as the default Git editor... although I am completely biased as a Vim user.

**Comment by drapergeek** [comment]
I think you should set this to sublime. I love vim but most people get very confused by the interface and having sublime show up would be fairly natural.

Granted, this may present issues with vagrant.

**Comment by kookster** [comment]
yes @drapergeek , I am mostly referring to vagrant users - agreed that subl on native makes much more sense.

**Comment by drapergeek** [comment]
I think in that case maybe we should set up a basic editor easier than vim. Something like nano maybe? I just know the number of people who freak out when getting stuck in vim.

**Comment by PDegenPortnoy** [comment]
Similar to @duggiefresh and @drapergeek; I am dedicated to vim, but I think it would be a mistake to introduce yet another complexity to those absolute novices who participate.  Consider that they are facing VM's, command line, SSH, shared folders, a text editor, SCM and deployment in addition to the core ruby and rails.  Poor kids.  I would support as simple a solution as possible to those who accidentally forget the "-m" when committing.  

The default of Nano, perhaps codified as a small sidebar in the instructions, does not seem too intimidating especially with the message of "If you remember the '-m' then you won't have this issue"  :-D

**Comment by kookster** [comment]
I agree with keeping nano default, but adding sidebar or some other place where there is obvious help for this situation.

**Comment by houhoulis** [comment]
@drapergeek +1

I don't know what's available within Vagrant.  Nano is not very intuitive, but it's still way more intuitive (less unpleasant to the newcomer) than vim.

**Comment by danchoi** [comment]
There is an even simpler alternative to nano for this problem. I posted a Gist here:

https://gist.github.com/danchoi/6874170

The solution involves 2 steps:
1. Write a simple Bash script to prompt user for a commit message if `-m` flag was not used.
2. Use `git config --global core.editor [editor]` to point to this script.

**Comment by drapergeek** [comment]
I like it! :+1:

**Comment by danchoi** [comment]
Moving this feature request to https://github.com/railsbridge-boston/railsbridge-virtual-machine/issues/2

Closing this issue here!
