### ISSUE TITLE
move git and heroku to the end?

### ISSUE THREAD

**Issue by kookster** [railsbridge-boston/railsbridge-boston#123]
I know that the inclusion of git has been semi-controversial, and certainly widely discussed.

I tend to think it is very important in introducing a basic developer skill set and workflow.

I was discussing this with some folks, and we came up with a suggestion to alleviate some of the confusion.

Should we move git and heroku deploy to the end of the day, and focus on running and developing locally before that?

**Comment by galiat** [comment]
I'm not sure how I feel about leaving git to the end, but I see merit in moving Heroku to the end. If heroku is moved to the end, I would want participants that need to leave early to be able to grab a TA before they leave to get whatever they worked on into heroku.

**Comment by kookster** [comment]
I agree.

While I am making the suggestion, I also think git is wicked important, and so is deploying your work and getting it out there.

I do see a kind of progression - I get my machine working, learn some basic ruby, then I use rails to make an increasing complex app, then at the end of the day I learn about how to do version control and deploy it for the world to see. (I would like to point out this is a literal use of the phrase 'at the end of the day' here.)

That story makes some sense to me, and makes me wonder if the version tracking and deployment add much throughout the day, or distract?  Is it not enough to run locally, and see changes there - how much more am I getting out of also pushing to heroku and seeing the same thing there?

As a counterpoint, a more realistic workflow to teach people is to always always always use git when starting a new project, commit early and often, learn to deploy incrementally, and get used to the feeling of exposure that comes with constant deployment of incomplete work.  These ideas also have great resonance, and I worry about compromising them.

**Comment by PDegenPortnoy** [comment]
I like the consideration of alternative work patterns; it helps highlight where boundaries lie.  With that in mind, I felt uncomfortable with the idea of postponing the use of SCM. Since we know that the most important things on our systems are the things we create, getting new developers into the habit of checking in completed code thoughts supports all the best practices with which we are familiar. 

I could see some advantage of not pushing heroku until later, but getting code checked in to git seems key.  That said, I didn't encounter much confusion between checking in and pushing to heroku.

**Comment by janetriley** [comment]
Done in #152 .  The current version of rails doesn't include the "welcome to Rails!" page in production, so the first deploy to heroku fails.  I moved it and git to its own unit.  

I agree that it's best to build good habits with git.  However, walking through the curriculum, git was introduced one page after introducing creating a project with rails.   I agree that it's a good habit to model, but I'd rather let someone settle in to rails more first.

The main RailsBridge repo has an intermediate curriculum.  That would be a great place to add regular commits.
