### ISSUE TITLE
Have an official "stretch chaplain" role

### ISSUE THREAD

**Issue by danchoi** [railsbridge-boston/railsbridge-boston#130]
I am a big fan of how Peter led the workshop in the midday stretch. I think we should have 3 of these stretch sessions throughout Saturday to keep people alert. It was also fun.

I propose we formalize this position & try to identify a TA or an attendee who can lead the class in short stretch sessions. There is bound to be a yoga or Pilates teacher in the group.

**Comment by ldamon** [comment]
This would be awesome!
I also think music could help in the same way, at intervals and at the start of the day, to break up the format and make it more fun.

**Comment by kookster** [comment]
Could I also suggest more coffee in the afternoon for the more caffeine inclined?

**Comment by danchoi** [comment]
Yes! I also noticed that we ran out of coffee and left some people
distraught. It would be easy next time to have an organizer run out to
Dunkin Donuts and bring back reinforcements.

**Comment by danchoi** [comment]
@ldamon I think some non-obtrusive background music during the breaks and lunch would be great.

**Comment by PDegenPortnoy** [comment]
Were the coffee systems on the counter not working?  We noticed on Friday night that they had a message to turn the water on.  Might it be possible to take advantage of those systems for the afternoon caffeine boost?

**Comment by kookster** [comment]
The machines were not working, and were not stocked.

**Comment by galiat** [comment]
I was not present for the bundle install part of the curriculum, but I generally like to use bundle install time to do a little stretching.

**Comment by houhoulis** [comment]
The systems on the counter were working on Saturday afternoon... barely.  I think it was a water pressure issue.  Combined, they were making about 6 cups of whatever per hour.

I think having more coffee of our own would scale better than trying to use those for everyone's afternoon coffee.  Plus, there's no guarantee they'd be stocked anyway.

**Comment by houhoulis** [comment]
I really like this ( @danchoi 's ) idea as well as the music idea.  @ldamon , feel free to file a music Issue.

**Comment by janetriley** [comment]
Corina Acosta has agreed to be stretch chaplain for the next workshop.   We're having an afternoon coffee break with Dunkin Donuts coffee.  Good suggestions.
