### ISSUE TITLE
Use VM for Linux too?

### ISSUE THREAD

**Issue by decklin** [railsbridge-boston/railsbridge-boston#140]
It may be a good idea to point even Linux users to a VM. The current LTS release of Ubuntu (for 3 more months, at least) ships Ruby 1.9.3, and it'd be better for Linux-using students to be up to date without having to deal with rvm or rbenv/ruby-build (or upgrading their distro). Not worrying about messing up your /usr/local is always good.

From the Vagrant downloads page: http://www.vagrantup.com/downloads.html it looks like they distribute a .deb, so we'd add a `dpkg -i` command to the steps. The most-user friendly virtualization provider is probably still VirtualBox; haven't looked at that.

Maybe revisit after January? We should have 8 Linux students (awesome!) and their experience may be instructive.

**Comment by decklin** [comment]
Still think this is probably a good idea so I will look into making it one option (Linux users love options) when I have some time to think about reorganizing/streamlining the pages where these downloads are.

**Comment by danchoi** [comment]
Hi @decklin 

Wanted to make sure that you know that some SF people are interested in using variations on this VM to aid volunteer hackfests on supporting software for Railsbridge such as Bridgetroll:
- https://groups.google.com/d/msg/railsbridge-workshops/NmAMlbGvNlY/qrOw0qZdxokJ
- https://groups.google.com/d/msg/railsbridge-workshops/-Io6h83U90k/Do7T_CA2HoMJ
- https://groups.google.com/d/msg/railsbridge-workshops/Fvmwcr6vnM8/s1tXJvsbOkkJ

From these threads, it looks like they had to leave Windows users out in the cold, unable to help out, for lack of a VM solution.

**Comment by decklin** [comment]
Reorganized the download page and install instructions to point to Vagrant/Virtualbox (use their preferred install method, whatever that may be), and also provide a reasonable amount of guidance for Linux students who want to build their own (we can give them the same tools that the VM uses to install Ruby). Any bugs we find in those installation methods, open as more specific issues.
