### ISSUE TITLE
purpose of Github for Windows unclear

### ISSUE THREAD

**Issue by decklin** [railsbridge-boston/railsbridge-boston#141]
Right now the pre-workshop Windows instructions say to install Github for Windows. Should OS X students install Github for Mac? What should Linux students do?

I think we should either:
1. Have Windows and OS X students create commits with the native Github app on their host machine (so add Github for Mac to instructions), and tell Linux students to use command-line git (in a regular shell, which means on their host machine if using a VM, see #140. We should tell Linux students to make sure git is installed with their package manager.)
2. Have everyone create commits inside the VM, with the version of git we distribute.

Option 2 sacrifices some initial ease of use for 90% of users (no GUI) but makes the process the same for everyone regardless of OS, eliminating "what git are you using?" conversations and student confusion over why their git looks different than the student next to them. I lean towards consistency.

Also, they really shouldn't have to worry about what Github is or sign up for it (unless that's changed?) -- for our purposes, git's for local revision control and pushing to Heroku. Unless you pay for an account, Github is for publishing code to the world which students may not be comfortable with just yet. You _can_ use the Github apps for a purely local/Heroku repo but they might ask you to sign up when they first run.

**Comment by danchoi** [comment]
FYI the only reason we installed GitHub for windows is to provide a
decent shell program for windows users. It didn't have anything to do with
git commands. All the git commands were done inside the VM using the Linux
command line

**Comment by danchoi** [comment]
I remember one thing to watch out for for windows users: When they run
github for windows for the 1st time, they need to configure it to provide a
launcher for a bash shell, and not Powershell.

**Comment by decklin** [comment]
Ah, got it. I'll just submit a small update to note that.

**Comment by slothbear** [comment]
Getting a decent shell was the main reason for Github for Windows – but
that reason includes a sub-reason... That decent shell comes with a
built-in SSH client. Windows doesn't have one installed by default as I
remember. The SSH client is required so a student can SSH into the VM.
