### ISSUE TITLE
Railsbridge VM git config modification 

### ISSUE THREAD

**Issue by danchoi** [railsbridge-boston/railsbridge-boston#144]
Whoever is modifying the VM might want to add this to the VM changes:

https://github.com/railsbridge/railsbridge-virtual-machine/issues/2

**Comment by decklin** [comment]
A ruby implementation is in the automated VM here: https://github.com/railsbridge-boston/railsbridge-boston-vm

If we are successful with the VM in this workshop, I can file off the couple bits that say "Boston" and ask RailsBridge HQ about having it be a common project for all locations. Will have to review the upstream curriculum to see if there's anything that needs to get in sync, but I think it's a good idea to not have it be Boston-specific.

**Comment by decklin** [comment]
Created https://github.com/railsbridge/railsbridge-virtual-machine/issues/9 to continue replacement discussion.
