### ISSUE TITLE
Inconsistent directory in vm_setup

### ISSUE THREAD

**Issue by bgiobbe** [railsbridge-boston/railsbridge-boston#148]
In the "Start and Connect Through The Commandline" section,
- Change `cd ~/Desktop/workspace`  to `cd ~/workspace` to agree with previous mkdir command;
- Change 'Commandline' to 'Command Line' in the heading.

**Comment by decklin** [comment]
Will be fixed by #150.

**Comment by janetriley** [comment]
Merged, closing issue.
