### ISSUE TITLE
installfest (/friday) link problems

### ISSUE THREAD

**Issue by intuedge** [railsbridge-boston/railsbridge-boston#151]
Chromebook notes are 404:
https://github.com/tdenkinger/docs/tree/nitrous.io/sites/installfest

[OS X < 10.5] link missing

**Comment by decklin** [comment]
Unfortunately it looks like that person deleted that branch. I'll just link to the nitrous.io site. If we have Chromebook students next time we can figure out what to do.

There is no more support for OS X versions prior to 10.5. That was the oldest version we had last time, and only a few students. I don't think anyone had older than 10.6 this workshop.
