### ISSUE TITLE
Moving away from this (railsbridge-boston) repo

### ISSUE THREAD

**Issue by mxie** [railsbridge-boston/railsbridge-boston#164]
With the [website redesign](https://github.com/railsbridge-boston/website) underway and [our attempt at merging](https://github.com/railsbridge-boston/docs) our material with the main RailsBridge content, I'd like to hear everyone's thoughts on no longer using this repo.

Here are my thoughts:
- The "marketing" content and the curriculum should be separate to make things less cluttered and more flexible to manage in the future.
- It would be good to keep the curricula together, whether we actually decide to use the "main version" or not.
  - Having the Ruby content and the Rails one point to two different places is just not ideal, especially from the student's standpoint.
- Having to sift through and figure out what's where and whether certain content is still being used is also a pain currently.
- I'd still like to keep this repo around, but note in the description and the README that we're no longer using this and then point to the appropriate places.
  - I think there's still a lot of great stuff that we might be able to pull out and into one of the other repos.

Thoughts? Suggestions? Feel free to add anyone else you think would have some good insight on this stuff.

@danchoi @bcarreno @decklin @janetriley

**Comment by danchoi** [comment]
Go for it!

**Comment by decklin** [comment]
Sounds great to me.

**Comment by mxie** [comment]
Started bringing over the Downloads and Installfest material over to the docs repo (via https://github.com/railsbridge-boston/docs/pull/15 - includes screenshots even!). Had to do some workarounds, but so far, so good.
