### ISSUE TITLE
http://docs.railsbridgeboston.org goes to a hover placeholder page

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge-boston/railsbridge-boston#166]
Hello!

I was hoping to show someone the RailsBridge VM instructions recently, but noticed that http://docs.railsbridgeboston.org/ is no longer running: 
![screen shot 2016-01-10 at 4 03 16 pm](https://cloud.githubusercontent.com/assets/978428/12224973/aef9d7be-b7b3-11e5-82de-cc50a0cf0069.png)

**Comment by mxie** [comment]
@lilliealbert This has been fixed! Thanks for putting in the issue.
