### ISSUE TITLE
Move initial "bundle install" to the installfest.

### ISSUE THREAD

**Issue by slothbear** [railsbridge-boston/railsbridge-boston#18]
Some students at today's workshop had trouble with the initial "rails new" command. Network troubles caused the command to time out during `bundle install`. Some folks had to issue the bundle command several times.

This kind of installation step seems more appropriate to the Install Fest. Waiting for stuff to complete. Network connections gone bad. Getting stuff installed!

**Comment by brendankemp** [comment]
I think pushing the `rails new` and `bundle install` stuff to Friday would be too much. I like the division of material as it is now. I think we are going to run into network issues no matter what. We _could_ run a local gem server. How hard would it be for the students to use that?

**Comment by slothbear** [comment]
I was reacting to the issues some had during the January workshop. I was excited to see `bundle install` on a more robust network yesterday to see if that would change my opinion. Maybe next time. I agree the division of material is good as it is.

**Comment by slothbear** [comment]
About the local gem server if we needed it... the server wouldn't need a copy of every gem known to the universe, just the rails dependencies.

**Comment by brendankemp** [comment]
Do you have experience setting up a gem server? How much configuration
would it require on the client side? Would the speed increase be
significant?

**Comment by slothbear** [comment]
I've no experience beyond observing some folks talk about size and time required to create a full local gem server. As long as the internet cooperates (like it did last weekend), I doubt a local server is worth the trouble. The local server looks pretty easy to set up though.

**Comment by danchoi** [comment]
See proposal in #86
