### ISSUE TITLE
Turn on auto save in Sublime Text

### ISSUE THREAD

**Issue by slothbear** [railsbridge-boston/railsbridge-boston#19]
A couple of students were accustomed to editors that automatically save files. When some change didn't take effect, they didn't realize their file had not been saved. The little circle on the file tab just wasn't enough info, heh.

Here's how to turn on autosave in Sublime Text. You might find the setting is already there, set to false.
- menu: Sublime Text2 -> Preferences -> Settings - User
- set "save_on_focus_lost": true

Reference:
http://blog.thekindof.me/2012/08/13/enable-auto-save-on-sublime-text-2/

**Comment by danchoi** [comment]
@slothbear Can you look at my commit and let me know it works and suffices? I haven't tested it.

**Comment by brendankemp** [comment]
Thanks @danchoi !

**Comment by brendankemp** [comment]
Could you open a PR?

**Comment by danchoi** [comment]
I made that commit to master. Did you want me to make PRs from now on?

**Comment by slothbear** [comment]
Yup -- @danchoi change worked for me. I also modified the issue to address Preferences -> Settings - User (instead of  - Default).

**Comment by bhoopal10** [comment]
it is not working
