### ISSUE TITLE
Suggestion from Andrew, Tracy, and Lauren: write up a behavior code

### ISSUE THREAD

**Issue by danchoi** [railsbridge-boston/railsbridge-boston#2]
We had a civility and sensitivity problem with one student on Saturday. We need to draft a civility policy for students to read, and maybe consent to on the workshop application. This policy should also be prominent on the workshop website.

**Comment by kookster** [comment]
I'll work on something, and send out for comment, based on a few suggested examples.  If anyone has other suggestions, let me know.
- Andrew

**Comment by danchoi** [comment]
Thanks @kookster !

**Comment by brendankemp** [comment]
I like the Steel City Ruby Conf Anti-harassment policy: http://steelcityrubyconf.org/policies#antiharassment. I think they did a good job of setting a tone by writing a strongly-worded statement, then linking it prominently in the conference materials. I heard they had an unusually friendly–and-safe-feeling conference because of it. Anyway, something to crib from, possibly.

Brendan

**Comment by kookster** [comment]
Great suggestion.

That policy is based on the guidelines from the geek feminism wiki, and
written by the leaders of the Ada Initiative - which is what I am also
consulting now.

http://steelcityrubyconf.org/policies#antiharassment
http://geekfeminism.wikia.com/wiki/Conference_anti-harassment
http://adainitiative.org/what-we-do/conference-policies/

I think the policy should be featured prominently; a prominent summary
statement on the homepage linking to the full policy perhaps?

Cheers,

-A

Andrew Kuklewicz

**Comment by kookster** [comment]
Reading up on this, another controversy is how photos/images from events
are used, and perhaps we should have a photo policy as well, and have
something about that and the anti-harassment policy as part of the
registration process as well.

http://geekfeminism.wikia.com/wiki/Photography

This has a write up of how some other events are addressing the issue:
http://adainitiative.org/2012/10/freely-available-conference-booklet-template-designed-to-welcome-women/

More things to think about, take seriously, and try to get right.

-A

Andrew Kuklewicz

On Sun, Nov 11, 2012 at 4:48 PM, Andrew Kuklewicz <andrew@beginsinwonder.com

> wrote:
> 
> Great suggestion.
> 
> That policy is based on the guidelines from the geek feminism wiki, and
> written by the leaders of the Ada Initiative - which is what I am also
> consulting now.
> 
> http://steelcityrubyconf.org/policies#antiharassment
> http://geekfeminism.wikia.com/wiki/Conference_anti-harassment
> http://adainitiative.org/what-we-do/conference-policies/
> 
> I think the policy should be featured prominently; a prominent summary
> statement on the homepage linking to the full policy perhaps?
> 
> Cheers,
> 
> -A
> 
> Andrew Kuklewicz
>

**Comment by brendankemp** [comment]
> I think the policy should be featured prominently; a prominent summary statement on the homepage linking to the full policy perhaps?

I definitely agree. I read the geek feminism guide, and I see they have more suggetions:

> Once you have adopted an anti-harassment policy, you should let people know about it. Here are some things you can do:
> Post the text on your event's web site.
> Link to the posted text from your CFP.
> Email the full text of the policy to all speakers who submit, and again when they're accepted.
> Publish it in your program materials - after the table of contents in your session handbook, for instance.
> Include it in the opening announcements for the conference.
> Print the text on a poster and hang it by the registration desk.

http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy_resources

**Comment by bcarreno** [comment]
Added a civility policy here
https://github.com/railsbridge-boston/railsbridge-boston/commit/6e8e7c6a11ab80ee4f491ca18b0a4c08b0c54225
