### ISSUE TITLE
Clarify a few things in installfest IRB and command line sections

### ISSUE THREAD

**Issue by janetriley** [railsbridge-boston/railsbridge-boston#20]
Some things were consistently misunderstood in the IRB and command line sections this weekend.    I've made changes to the markdown in my fork and am about to submit a pull request.  

Please see
https://github.com/janetriley/railsbridge-boston/commit/5b2b5b1c4933bd5c3e076b0ddecd80080a29c422
and
https://github.com/janetriley/railsbridge-boston/commit/c2844b935b937eae16719a2e7e32255ce120b0a8

for the specifics.

**Comment by brendankemp** [comment]
These are very good, thank you for them.
