### ISSUE TITLE
Dylan's recap rocks; can we tweak picture sizes?

### ISSUE THREAD

**Issue by danchoi** [railsbridge-boston/railsbridge-boston#26]
Dylan's recap rocks!

Not a big deal, but can we tweak the photo sizes so they fit the layout grid?

We just need the images to be the same size as the older picture of the laptop with the RailsBridge stickers on it. If someone can put larger images in the `public/images/jan_2013` directory, I can scale them to the right size with the command line `convert` command from ImageMagick

**Comment by bcarreno** [comment]
Yes, please.

**Comment by dylancashman** [comment]
Hey, good point.  I can get to this in a bit.  I'll just pull larger versions.

**Comment by dylancashman** [comment]
I'm a little confused.  I replaced all images with increased size versions locally, and then committed and pushed.  I don't see them in the diff, though.

https://github.com/railsbridge-boston/railsbridge-boston/commit/e1ffc9632f770a8ab1604b7bb2cfadfe771a36fd

Does someone know what I did wrong here?

**Comment by danchoi** [comment]
You did it correctly. We can push!

**Comment by danchoi** [comment]
Can someone push to production if everything looks good? My laptop is nearly out of battery.

**Comment by bcarreno** [comment]
There's something @brendankemp has to check and we'll deploy

**Comment by brendankemp** [comment]
Getting out of work soon—I'll take a look when I get home.

**Comment by danchoi** [comment]
I'm leaving it confidently to you guys. I got excited.
