### ISSUE TITLE
Heroku Gem

### ISSUE THREAD

**Issue by drapergeek** [railsbridge-boston/railsbridge-boston#5]
Let me preface this issue by saying how much I enjoyed the workshop and how impressed I was by everything that went into the workshop.  I really think it was a lot of fun and every participant I spoke with was very happy.  I can't wait to help out again!

I made a few notes on things that I think we can either fix or improve and I plan on putting them in as issues so I can solicit feedback and if people agree I'm more than happy to put in the PRs, just don't want to do the legwork if I'm in the minority on the opinion!

Feel free, to turn me down or disagree, these are only opinions and once again, great job!

The actual issue:  we should update the documentation to not actually download the heroku gem but to specify to download and install the heroku toolbelt.

**Comment by danchoi** [comment]
@drapergeek thank you a ton for helping out by teaching. It made a big difference. I will never ever call you "the thoughtbot dude" again! :)

These notes are awesome & very well thought out. Thank you. I will let @brendankemp and others comment more specifically on them.

**Comment by brendankemp** [comment]
@drapergeek thanks for the notes. These are a big help.

>  we should update the documentation to not actually download the heroku gem but to specify to download and install the heroku toolbelt.

I thought this too, and updated the instructions to say so. Then one of the curriculum testers said that the Toolbelt actually installs its own Ruby, placing it before rbenv in the PATH, and causing all sorts of problems. People installing the Toolbelt when they signed up for a Heroku account was a source of problems during the installfest, so I had to add a warning to NOT download the toolbelt when asked.

**Comment by drapergeek** [comment]
I wasn't aware of that, I walked a few people through and these seemed to work out fine (not arguing, only adding my experiences).  I feel like before the next workshop (approximately a month ahead of time).  We should completely walkthrough and test these steps and update.  I'm sure in the 3 months the landscape will change.  Also, the rails installer we're recommending for mac os uses rvm so I'm sure that will change a few things.

Also, given that we're using rvm for railsinstaller,I would recommend this for linux as well to keep things consistent.

**Comment by mauricio** [comment]
I saw the `rbenv` issue with the toolbelt and also asked people to keep the them instead of using it.

We should surely test this in as many machines as possible and see if we can reproduce it.

**Comment by drapergeek** [comment]
I'm going to attempt to set up a Mac OS VM that only uses the Railsinstaller(no xcode/gcc) and then installs heroku toolbelt.  Can someone else try this same setup on windows and report back?

**Comment by slothbear** [comment]
The current Heroku Toolbelt contents lists Heroku client, Foreman, and git. When I installed the toolbelt recently, it didn't appear to add git to my system (since I already had git?). And no mention of ruby. This weekend some students had trouble with the Heroku gem, so they used Heroku Toolbelt. I didn't help any of those students – perhaps someone who did could comment on how it went?

I like Jason's idea of curriculum/tools walkthrough before each workshop, and I'm happy to help with that. For now, I'll add the walkthrough to the Task Responsibilities wiki page under curriculum.

**Comment by slothbear** [comment]
Heroku Toolbelt includes generation of the ssh key. That would shave a couple of steps off of our instructions.

I looked into the toolbelt's **ruby** usage. It does still install it's own version of Ruby, but as far as I can tell, the new Ruby is only used by the toolbelt.

https://toolbelt.heroku.com

**Comment by drapergeek** [comment]
I say we go ahead and replace it. We had to install it for a lot of people at the workshop this time due to problems with SSL.
