### ISSUE TITLE
Specify proper ruby version in Gemfile and .ruby-version file.

### ISSUE THREAD

**Issue by drapergeek** [railsbridge-boston/railsbridge-boston#50]
It would be ideal to specify the proper version in both locations to make it easier on anyone working with the repo.

@danchoi can you confirm the version of ruby that is being used on heroku now so we can create these files?

**Comment by danchoi** [comment]
The heroku app is running on 1.9.2. Feel free to add the dotfiles and even
bump up the Ruby.

**Comment by houhoulis** [comment]
Pull request https://github.com/railsbridge-boston/railsbridge-boston/issues/51 submitted to resolve this issue.
