### ISSUE TITLE
Add information about submitting issues for TAs.

### ISSUE THREAD

**Issue by drapergeek** [railsbridge-boston/railsbridge-boston#60]
This is primarily a reminder so I do not forget about it.

We should have information on the TA information about how to file bugs and encourage our TAs to do so, even during the event. I feel like there is a lot of lost information after the workshop and encouraging immediate issue tracking would be helpful.

**Comment by slothbear** [comment]
In addition – I'll include a plea to contribute issues when I send the Railscasts Pro coupon to staff in the next couple days.

**Comment by drapergeek** [comment]
Yes please.
