### ISSUE TITLE
Completion Script

### ISSUE THREAD

**Issue by drapergeek** [railsbridge-boston/railsbridge-boston#61]
Spitballing ideas here so feel free to provide an opinion!

I would love to see a small script that we can have each participant run after they think they are setup, that would walk them through a set of objectives and confirm that they are finished. This information could not only be shown to the TA but  we could also potentially send the information to our site to track if we wanted to.

Things that we should do in this script:
- verify a version of ruby
- verify a version of rails.
- verify the heroku toolbelt works properly
- verify that a new rails app can be bundled

**Comment by slothbear** [comment]
_Love_ this idea. I love systems that come with self-auditing commands, like `brew doctor`.
