### ISSUE TITLE
Add a command line session for windows

### ISSUE THREAD

**Issue by drapergeek** [railsbridge-boston/railsbridge-boston#65]
Despite being nearly identical, I had a few students say they wanted a separate command line for windows session just so they could feel like we were covering all areas.

This may have just been a failure to really explain that the session applied to windows. Just putting this out there for discussion.

**Comment by danchoi** [comment]
Proposal in #86 would put everyone regardless of laptop OS on Ubuntu command line.

**Comment by janetriley** [comment]
Since we rolled out Vagrant ( per #86 ),  and since the issue is 5 months old, I'm going to close this issue.   Please re-open if it still needs attention.
