### ISSUE TITLE
Please claim your project on Ohloh.net

### ISSUE THREAD

**Issue by PDegenPortnoy** [railsbridge-boston/railsbridge-boston#71]
RailsBridge Boston has a project page on Ohloh.net: https://www.ohloh.net/p/railsbridge-boston

Please come to Ohloh and claim your contributions as well as become the managers of the RailsBridge Boston project.

**Comment by bcarreno** [comment]
Thanks for coming to the class and setting us in Ohloh.net.  I think I did everything to claim the project.
