### ISSUE TITLE
Git Extra Credit

### ISSUE THREAD

**Issue by drapergeek** [railsbridge-boston/railsbridge-boston#8]
I think that the git extra credit section which involves branching could be better used on a rails idea or principle.  I think that (unless I'm wrong) for the most part we should stick to git as a means to an end for the workshop and try to focus on rails/ruby.

Most of the students I worked with seemed to be confused about what they had done and didn't really see any benefit in the extra credit but seemed to enjoy a lot of the other.  

I'm not sure how everyone else was but I would say that almost all my participants seemed to get to the extra credit sections.

**Comment by brendankemp** [comment]
I like this thinking. @drapergeek do you have any ideas for a Rails principle that would be worth covering?

**Comment by drapergeek** [comment]
Personally I like #9 as the replacement for this.
