### ISSUE TITLE
Version mismatch between RailInstaller and Vagrant

### ISSUE THREAD

**Issue by bgiobbe** [railsbridge-boston/railsbridge-boston#96]
The InstallFest checklist indicates that we've been using Rails 3.2, but the new Vagrant virtual machine includes Ruby 2 and Rails 4.

```
Last login: Mon Sep 16 22:31:30 2013 from 10.0.2.2
vagrant@precise32:~$ ruby -v
ruby 2.0.0p247 (2013-06-27 revision 41674) [i686-linux]
vagrant@precise32:~$ rails -v
Rails 4.0.0
```

**Comment by bcarreno** [comment]
@danchoi to avoid unexpected issues, I think it would be better using Ruby 1.9.3 and Rails 3.2 across the board.  Would it be difficult to generate a VM on 1.9.3/3.2?  CC: @janetriley @mxie

**Comment by danchoi** [comment]
Not difficult, but we need to find a better way to serve the VM download. A torrent might be a good idea.

**Comment by bcarreno** [comment]
I can do the hosting of the image this weekend, I'll update the repo.

When do you think you can have the new image? @janetriley was planning to test the installation on Windows this weekend

**Comment by danchoi** [comment]
I create a new vagrant image for Rails 3.2 and uploaded it to a slow
server. You can download it from http://66.228.42.213/railsbridgevm-3.2.box

**Comment by bcarreno** [comment]
Setup images on S3 and updated the links.
Sizes are very different, @danchoi can you confirm sizes and SHA-1 (I'd like to display a digest in the repo)

``` text
387813770  /Users/bcarreno/Downloads/railsbridgevm-3.2.box
606974473  /Users/bcarreno/Downloads/railsbridgevm-4.0.box
bd347fd3ca823bc27b6716fcab344816b35b6bdd  /Users/bcarreno/Downloads/railsbridgevm-3.2.box
293c4e052827bbbe265ba3b2e5436d67d510bb2e  /Users/bcarreno/Downloads/railsbridgevm-4.0.box
```

**Comment by danchoi** [comment]
The 3.2 box is much smaller because I learned a new technique for shrinking
the image.

**Comment by danchoi** [comment]
3.2 box is around 370MB
4.0 box is over 500MB

**Comment by danchoi** [comment]
Closing, we have a 3.2 box in the cloud.
