### ISSUE TITLE
Proposal for curriculum change on Friday night 

### ISSUE THREAD

**Issue by danchoi** [railsbridge-boston/railsbridge-boston#98]
I'd like to propose splitting the installfest into 3 stages. 
1. Start downloading other install downloads if they haven't done so before the workshop. Windows people should have GitBash installed already. Open a Terminal in OS X or GitBash/Windows or Linux.
2. Do the Command line lecture. Everyone must listen.
3. Rest of installfest

The rationale for this is that in the past half the room would not be listening to the command line lecture because they were busy doing the installation. What made it worse was when there was background chatter from TAs trying to help those people.

**Comment by alexch** [comment]
This is why we have a separate night for installfest. It's not feasible to
have a lecture and install chaos.

On Wed, Sep 25, 2013 at 10:37 AM, Daniel Choi notifications@github.comwrote:

> I'd like to propose splitting the installfest into 3 stages.
> 1. Start downloading other install downloads if they haven't done so
>    before the workshop. Windows people should have GitBash installed already.
>    Open a Terminal in OS X or GitBash/Windows or Linux.
> 2. Do the Command line lecture. Everyone must listen.
> 3. Rest of installfest
> 
> The rationale for this is that in the past half the room would not be
> listening to the command line lecture because they were busy doing the
> installation. What made it worse was when there was background chatter from
> TAs trying to help those people.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/railsbridge-boston/railsbridge-boston/issues/98
> .

## 

Alex Chaffee - alex@stinky.com
http://alexchaffee.com
http://codelikethis.com
http://twitter.com/alexch

**Comment by danchoi** [comment]
I pushed a first draft of the pre-workshop download guide at [http://www.railsbridgeboston.org/pre_workshop](http://www.railsbridgeboston.org/pre_workshop). We'll need to edit the [Friday installfest instructions](http://www.railsbridgeboston.org/friday) a little bit more to align the two parts.

@alexch Boston has always done one command line and text editor mini-lecture on Installfest night, because cramming those mini-lectures into Saturday would possibly over-fry brains.

**Comment by kookster** [comment]
Maybe add an abbreviated cmdline reminder to Saturday? Focus on irb vs. shell (how to start, recognize which is running, and end them), traversing directories, and importance of home and workspace dirs?

**Comment by janetriley** [comment]
The next workshop shoould approximate this. 
We'll do a group walkthrough of installation on Friday. 
There's a  more detailed command line page in the Ruby curriculum at  https://github.com/railsbridge-boston/docs .
